### ISSUE TITLE
Decide future of hapi hawk plugin

### ISSUE THREAD

**Issue by hueniverse** [mozilla/hawk#272]
This includes both the hawk module and the hapi hawk authentication plugin. If you are not going to maintain the plugin, I suggest removing it from the repo and publishing this as a new major version.

**Comment by djmitche** [comment]
Sounds good.  I assume hapi is using the `@hapi/hawk` package anyway, so what I publish to `hawk` won't matter?

**Comment by hueniverse** [comment]
`@hapi/hawk` has been deprecated so while people can continue using it, it is no longer maintained. If you remove that code from this repo, it will not be maintained by anyone.
